version: 1
services:
  - type: web
    name: discord-bot-hendra-coders
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    env:
      DISCORD_TOKEN: ${DISCORD_TOKEN} # Pastikan untuk mengatur ini di environment variables Render.com
    autoDeploy: true
    instanceType: micro
    region: oregon
    
